'''
Manages the signal model.
'''

# ? IMPORTS
from datetime import datetime


# & CLASS INIT
class Signal:
    '''
    Represents a signal generated by a strategy.
    '''

    BUY = "BUY"
    SELL = "SELL"

    # * CONSTRUCTOR
    def __init__(
        self, symbol: str, entry_time: int|datetime, entry_price: float,
        type: str, sl: float, tp: float, strategy: str, risk: float|None = None, reward: float|None = None
    ):
        self.symbol = symbol
        self.entry_time = entry_time
        self.entry_price = entry_price
        self.type = type
        self.sl = sl
        self.tp = tp
        self.strategy = strategy
        self.risk = abs(self.entry_price - self.sl) if risk is None else risk
        self.reward = self.entry_price + abs(self.tp) if reward is None else reward
        self.lot_size = 0

    # * STRING REPRESENTATION
    def __str__(self):
        return f"{self.symbol} | {self.entry_time} | {self.entry_price} | {self.type} | sl={self.sl} | tp={self.tp} | {self.strategy} | {self.risk} | {self.reward}"